### ISSUE TITLE
Android Gradle Plugin Compatibility Issue 

### ISSUE THREAD

**Issue by Khuza1ma** [kakerublaze/otaku-club#9]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':wakelock' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by taherdodia03** [comment]
you just need to upgrade your flutter version to 3.24.2 as of latest now and it will be resolved
